### ISSUE TITLE
[Ontology] Update D3-SPP Artifact Mappings.

### ISSUE THREAD

**Issue by netfl0** [d3fend/d3fend-ontology#1]
Contributor:
Why is Strong Password Policy not mapped to Password Cracking in the Knowledge Graph?

**Comment by hack-sentinel** [comment]
Reviewed and modified Credential Access Technique, Brute Force, and Brute Force subclasses to indicate more precisely the main digital artifacts being accessed (here tested by some means of trial and error.)  Result with query from D3-SPP now results in new matches the the password-specific classes under Brute Force.

![image](https://user-images.githubusercontent.com/101665567/167186614-e81a426e-263a-4f00-a617-a61f735c563c.png)
