### ISSUE TITLE
Move definitions from rdfs:comment to d3f:definition

### ISSUE THREAD

**Issue by hack-sentinel** [d3fend/d3fend-ontology#108]
- [x] Review for duplicate comments on classes and properties 
   Only two classes found with dupes: {Weakness, OperatingSystemConfigurationFile}
- [x] Verified d3f:comment items were only developer comments for future reference
- [x] De-dupe any true duplicates (rdfs:comment pairs)

After completion rdfs:comment assertions will simply be ordinary comments and may be duplicates.

- [x] Will require mod to be coordinated with other components d3fend-frontend and/or d3fend-frontend before final merge. (see comment below for additional choices before merging.)

**Comment by hack-sentinel** [comment]
serializer 1.2.1 is now what results from "make install-deps" command.  This appears to be create diffs beyond minimal ones 1.2.0 used to create.  Also, reversion either from Protege use, robot use, or serializer to have ^^xsd:anyURI add to type some strings and conversion to ^^xsd:string for versions of controls rather than recent change to integers.

**Comment by netfl0** [comment]
You can merge, I'll update frontend.

**Comment by netfl0** [comment]
I think i got all the references.

Some SPARQL vars still exist as "comment" rather than definition, but the ui generally has reformed those into "definition" {comment value} anyway.
