### ISSUE TITLE
Asset Inventory: technique or tactic

### ISSUE THREAD

**Issue by ioggstream** [d3fend/d3fend-ontology#12]
## Question

an Asset Inventory which maps to `nist:Identify` should be considered a tactic or a technique?

Related to #4 cc: @Glenn1963l

**Comment by Glenn1963l** [comment]
Still in development, but Asset Inventory will be a countermeasure under a Tactic called Model.

**Comment by ioggstream** [comment]
I'd be happy to review the PR!

**Comment by hack-sentinel** [comment]
Pre-release tweak to Model tactic: Revised definition of Model tactic, Renamed technique to Asset Vulnerability Enumeration (not Assessment), and fixed broken sentences for definitions of two inventory techniques
