### ISSUE TITLE
Improve User defintion to bias less toward human users and include more agent/entity terminology

### ISSUE THREAD

**Issue by netfl0** [d3fend/d3fend-ontology#139]
### Discussed in https://github.com/d3fend/d3fend-ontology/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **dsdr0** March 13, 2023</sup>
**User - Object Properties** & **User Account - Object Properties** 
States user is a person [or agent] but believe it should explicitly include Non-Person Entities (NPEs), also known as non-users in some circles. There is an important distinction between the two sets of users within many policies/requirements. 

** User Account - Object Properties ** 
To include NPEs and lack of "login", suggest changing "login" language to authenticate. I would either remove login example or expand examples to include a web application example (or something else).</div>

**Comment by ag0x00** [comment]
Related: `:UserAction` versus non-user-initiated tasks and commands.
MS uses "Machine Action".

**Comment by netfl0** [comment]
complete, Agent now part of Ontology. also covers NPE
