### ISSUE TITLE
New Digital Artifact: User Group

### ISSUE THREAD

**Issue by ryantxu1** [d3fend/d3fend-ontology#154]
## Digital Artifacts
User Group

## Definition
A collection of multiple user accounts that share the same access rights to the computer and/or network resources and have common security rights (https://www.digitalcitizen.life/simple-questions-what-user-group-windows-what-does-it-do/)

User Groups can contain group policies

**Comment by ioggstream** [comment]
Probably this requires some more thinking,
Eg. Maybe a group is related to policies but does not contain them...

**Comment by netfl0** [comment]
Agree, I had him change that with additional commits, please confirm.

**Comment by ryantxu1** [comment]
yes it's changed, the properties are what @netfl0 had listed in his comment
