### ISSUE TITLE
New Technique Grouping: Restore

### ISSUE THREAD

**Issue by kelby-shelton** [d3fend/d3fend-ontology#173]
**Note: all sections are required.**

# Restore
A new technique grouping for techniques that follow the category definition stated below.

## Digital Artifacts
N/A

## Definition
Restoring systems, networks, and information, to a functioning state after an Attacker has been evicted.

CISA 508C Federal Government Cybersecurity Incident and Vulnerability Response Playbooks describes Recovery as:

> Restore systems to normal operations and
> confirm that they are functioning normally. The
> main challenges of this phase are confirming that
> remediation has been successful, rebuilding
> systems, reconnecting networks, and recreating
> or correcting information.

## How it works
CISA gives the following examples or Recovery Actions:

> • Reconnecting rebuilt/new systems to
> networks.
> • Tightening perimeter security (e.g.,
> firewall rulesets, boundary router access
> control lists) and zero trust access rules.
> • Testing systems thoroughly, including
> security controls.
> • Monitoring operations for abnormal
> behaviors.

## Considerations
NIST 800-61r2 notes that Attackers often try to attack the same resource again. They state:

> Once a resource is successfully
> attacked, it is often attacked again, or other resources within the organization are attacked in a similar
> manner.
> Eradication and recovery should be done in a phased approach so that remediation steps are prioritized.
> For large-scale incidents, recovery may take months; the intent of the early phases should be to increase
> the overall security with relatively quick (days to weeks) high value changes to prevent future incidents.
> The later phases should focus on longer-term changes (e.g., infrastructure changes) and ongoing work to
> keep the enterprise as secure as possible

## References
https://www.cisa.gov/sites/default/files/publications/Federal_Government_Cybersecurity_Incident_and_Vulnerability_Response_Playbooks_508C.pdf
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-61r2.pdf

**Comment by netfl0** [comment]
Initial cut in: 

6f3177ab08412b3cb401828a5671ec2b27856400
