### ISSUE TITLE
Refactor build/d3fend.csv to use local robot/sparql without making rest calls, python if necessary

### ISSUE THREAD

**Issue by netfl0** [d3fend/d3fend-ontology#177]
[build/d3fend.csv: build/d3fend-public.owl ## make D3FEND csv, not part of build or all targets](https://github.com/d3fend/d3fend-ontology/blob/develop/Makefile#L273)

This will reduce the CI/CD complexity.

**Comment by ryantxu1** [comment]
@netfl0 can close this now
