### ISSUE TITLE
Evolve functionality for updating attack techniques 

### ISSUE THREAD

**Issue by nav6402** [d3fend/d3fend-ontology#187]
Support:

- Getting attack data using stix2 
- Improved flow (create copy of d3fend-protege.ttl, put all updates in copy, then ask user to manually compare before replacing)
- Adding new techniques to d3fend-protege.ttl
- Handling deprecated techniques -> (owl:deprecated true, rdfs:comment 'explanation for why deprecated')
- Handling revoked techniques -> (owl:deprecated true, rdfs:comment 'This technique was revoked by ...', rdfs:seeAlso technique revoked by)
- Alternative way to add techniques other than ./bin/robot
- Many test cases 

Child issues: 
- #77
- #137

**Comment by netfl0** [comment]
works for me, tried a new ontology &  website build.

Nice work!
