### ISSUE TITLE
[Correction] Typo in mapping for resource development tactic

### ISSUE THREAD

**Issue by aw350m33d** [d3fend/d3fend-ontology#203]
Hey!
I noticed an inaccuracy in the restrictions.
Resource development techniques must enable resource development tactic.

https://github.com/d3fend/d3fend-ontology/blob/e685e915f519c573a74c5b480de16c904e9154c4/src/ontology/d3fend-protege.ttl#L15844

If there are no objections, I can create PR with fix.

**Comment by aw350m33d** [comment]
It also seems that the problem is in the :display-order of tactics starting with InitialAccess because the :ResourceDevelopment tactic [does not have this DataProperty](https://github.com/d3fend/d3fend-ontology/blob/e685e915f519c573a74c5b480de16c904e9154c4/src/ontology/d3fend-protege.ttl#L15835).

And for consistency in the description of tactics, it would be nice for [Reconnaissance to add rdfs:label](https://github.com/d3fend/d3fend-ontology/blob/e685e915f519c573a74c5b480de16c904e9154c4/src/ontology/d3fend-protege.ttl#L15588).

**Comment by netfl0** [comment]
Feel free to create PR. Thank you and good finds.
