### ISSUE TITLE
HPKP deprecated in favor of Certificate Transparency

### ISSUE THREAD

**Issue by ioggstream** [d3fend/d3fend-ontology#23]
## I expect

To mention that https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning is deprecated.

Add suitable references to Certificate Transparency.

**Comment by netfl0** [comment]
note: the change is here

https://github.com/d3fend/d3fend-ontology/commit/c91dbaa7b364f6695e164372bca3e8b3b163ec63#diff-c9e7a3b5c8509ab3baab259fd3b54f3b3c82fb12d6858868d1f253d0aad105e7R19452

Protege is introducing spurious changes in the ttl file if there multiple predicates, it non-deterministically sorts their values. @hack-sentinel and I are looking for a solution to that problem.

**Comment by ioggstream** [comment]
@netfl0 that was quick! Thanks anyway. 

For the sorting issue, probably a code formatting/linting tool can take care of it.

If you are interest in a pre-merge review, feel free to file a pull request and tag me.
