### ISSUE TITLE
[Correction] Typo in definition of OSAPISystemFunction

### ISSUE THREAD

**Issue by swartik** [d3fend/d3fend-ontology#235]
In src/ontology/d3fend-protege.ttl, the definition of `:OSAPISystemFunction` reads:

    Indirect System calls are made through OS-specific libraries (like glibc in Linux) that provides a higher-level API for the system calls.

The plurality of "libraries" and "provides" don't match.

**Comment by netfl0** [comment]
merged

**Comment by netfl0** [comment]
thank you!
