### ISSUE TITLE
Review behavior of Neighbors panel on Access Mediator artifact page for mediates-access-to Resource

### ISSUE THREAD

**Issue by hack-sentinel** [d3fend/d3fend-ontology#254]
In the Neighbors panel of the d3f:AccessMediator artifact page, there is a relationship name "mediates-access-to" that is tied to the Access Mediator and Resource artifacts but the Access Mediator artifact does not show on the website and the Resource Artifact doesn't show a _mediates-access-to_ relationship.  

* Note: This have been an issue for 0.14.0 but resolved in 0.15.0, TBD after contact and follow-up with originator.

Ref page: https://d3fend.mitre.org/dao/artifact/d3f:AccessMediator/

**Comment by hack-sentinel** [comment]
Update:

- [x] The corresponding Resource artifact doesn't show a _mediates-access-to_ relationship on its page.  [This is no longer present as of at least 0.15.0.]

- [ ] In the Neighbors panel of the d3f:AccessMediator artifact page, there is a relationship name "mediates-access-to" linking the Access Mediator and Resource artifacts... but the AccessMediator box depicted does not link to itself and is instead undefined (a 404 page.)

**Comment by netfl0** [comment]
fixed in other repo
