### ISSUE TITLE
Password management hints beyond NIST SP 800 63

### ISSUE THREAD

**Issue by ioggstream** [d3fend/d3fend-ontology#39]
## Discussion

- check if this doc https://www.cs.umd.edu/~jkatz/security/downloads/passwords_revealed-weir.pdf provides a valuable kb
-

**Comment by netfl0** [comment]
Yes, the references are not an endorsement of any particular guidance or specification. They are meant to inform. D3FEND can be used in guidance issued by others for consistent terminology, but D3FEND is not guidance itself.
