### ISSUE TITLE
Which artifact for an Executable interpreter

### ISSUE THREAD

**Issue by ioggstream** [d3fend/d3fend-ontology#40]
## Question

Which artifact maps to an executable interpreter e.g. Java Virtual Machine or Python?

1. :ExecutableFile mentions "in a more general sense, a file containing instructions (such as bytecode) for a software interpreter may also be considered executable" :thinking: 
2. :ExecutableScript mentions that a script "is different from an ExecutableFile :+1: 

afaik

1.  java do not fall into this model since it executes bytecode (assembled by somebody else)
2.  python currently converts it into bytecode before executing, but this is just nitpicking

## Note

This is useful to define the artifacts associated to python and java libraries, and to answer to the following questions:

- interpreted and bytecode libraries should be associated to different artifacts?
- since dependencies might contain shared libs, could a more general concept of "application dependency" be useful in this case? 
- could the above artifact (ApplicationDependency) apply to source code dependencies that are statically compiled at build time together with the application code (e.g. golang?)

**Comment by netfl0** [comment]
> 



> 



> ## Question
> 
> Which artifact maps to an executable interpreter e.g. Java Virtual Machine or Python?
> 
>     1. :ExecutableFile mentions "in a more general sense, a file containing instructions (such as bytecode) for a software interpreter may also be considered executable" 🤔
> 
>     2. :ExecutableScript mentions that a script "is different from an ExecutableFile 👍
> 
> 
> afaik
> 
>     1. java do not fall into this model since it executes bytecode (assembled by somebody else)
> 
>     2. python currently converts it into bytecode before executing, but this is just nitpicking
> 
> 
> ## Note
> 
> This is useful to define the artifacts associated to python and java libraries, and to answer to the following questions:
> 
>     * interpreted and bytecode libraries should be associated to different artifacts?

Thus far, we have not needed the distinction, but with the contributions you're working on, it is clear we need the additional types. Agree?

> 
>     * since dependencies might contain shared libs, could a more general concept of "application dependency" be useful in this case?
Yes, I was thinking something like Software Library, which would contain Software Library Files( we already have  -> Shared Library File).  Software Libraries might also contain configuration files as well. These would be similar to but distinct from Application Configuration Files.

> 
>     * could the above artifact (ApplicationDependency) apply to source code dependencies that are statically compiled at build time together with the application code (e.g. golang?)

Yes, golang is incorporating them into the resulting Executable Binary. We might want to create a subcass to address these sorts of packages, they would `contain` Software Libraries which `contain` Software Library Files`.  The contain relation is a bit of an issue here. One thing we have been considering is a relationship like `derived-from` to indicate that its not likely the exact same as the originating information bearing entity.

Excellent points @ioggstream 

cc @hack-sentinel

**Comment by ioggstream** [comment]
1. in [https://next.d3fend.mitre.org/dao/artifact/d3f:ExecutableBinary/](ExecutableBinary) we have 

*D3FEND also considers byte code for a virtual machine to be binary code. This is in contrast to executable scripts written in a scripting language.*

2. This includes library.pyc but not library.py

**Comment by netfl0** [comment]
**Simple reduction:**

ExecutableBinary:
kernel -> execv(equivalents) -> ExecutableBinary(ELF,PE32) -> (process has launched)

For JARs or Scripts:
                                                         (bin/java|python etc)
kernel -> execv(equivalents) -> ExecutableBinary(ELF,PE32) -> Executable Script/Archive -> (process has launched)

We need an ExecutableLibrary, and possibly a ExecutableArchive as a subclass
    ExecutableLibrary -> ExecutableArchive

**Comment by hack-sentinel** [comment]
Closing as ioggstream's content on #45 to develop.  Will add ticket for consideration "Add an ExecutableLibrary, and possibly a ExecutableArchive class as a subclass; ExecutableLibrary -> ExecutableArchive"
