### ISSUE TITLE
IO Port Restriction (D3-IOPR) expanded definition and link to ATT&CK T1200 Hardware Additions 

### ISSUE THREAD

**Issue by captainron9** [d3fend/d3fend-ontology#48]
Recommending the definition of IOPR be expanded to Port Security and MAC address restrictions for additions of new devices or hardware to the network. Through this expanded definition, D3-IOPR should protect against T1200 Hardware Additions.

**Comment by netfl0** [comment]
Thank you for your contribution! We agree, we'll get this updated.
