### ISSUE TITLE
Hardware Additions (T1200) is in lookups but not registering in d3fend-full-mappings.{json,csv}

### ISSUE THREAD

**Issue by hack-sentinel** [d3fend/d3fend-ontology#54]
For example, "T1200" is found in the ATT&CK Extractor, but there is no reference to T1200 in the .csv or .json mappings on the https://d3fend.mitre.org/resources/ontology/ (h/t Dean Tate)

**Comment by netfl0** [comment]
This doesn't show up because there were no mappings. Plan to migrate full mapping inference data files into large construct query, lets create a new ticket for that one.
