### ISSUE TITLE
Unable to execute 'make all'

### ISSUE THREAD

**Issue by DramaticallyDecayed** [d3fend/d3fend-ontology#56]
Hi!

I couldn't execute 'make all' as is: there is no access to 'https://d3fend.pages.mitre.org/deps/robot/robot.jar'. So, instead I've used 'https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar'.

Thank you!

**Comment by hack-sentinel** [comment]
Update (and test) with robot.jar dependency (ROBOT_URL) pointing to https://github.com/ontodev/robot/releases/tag/v1.9.0.   [Note: Current internal and tested builds using https://github.com/ontodev/robot/releases/tag/v1.8.1.]
