### ISSUE TITLE
CWE Integration and Relationships

### ISSUE THREAD

**Issue by netfl0** [d3fend/d3fend-ontology#66]
Integrate CWE's definition of weakness into D3FEND ontology, relate weaknesses to relevant D3FEND Digital Artifacts and components.

**Comment by ioggstream** [comment]
@netfl0 shouldn't CWE be managed in a separate file and have a specific namespace? https://github.com/d3fend/d3fend-ontology/compare/feature/netfl0-66-cwe-integration-and-relationships#diff-c9e7a3b5c8509ab3baab259fd3b54f3b3c82fb12d6858868d1f253d0aad105e7R2811 

Conflating everything in a single file hinders manageability. Moreover, I suggest having a script that generates the CWE taxonomy out of an authoritative file. The CWE ttl can then be generated by the CI in this repo.

WDYT?

**Comment by netfl0** [comment]
> 

Q1:
Totally agree, however we chose to do this for the near-term intentionally. While there are technical solutions for solving this problem, they tend to be hurdles for newbies and we want to make things very easy. catalog files in particular :)

We intend to address this in the future. Is there an example of the hindrance? 

Q2:
The subroutine taxonomy is related to CWE but I would not say derived from.

**Comment by ioggstream** [comment]
> Is there an example of the hindrance?

1. CWE updates require merges on the d3fend.ttl, which is already huge;
2. I can provide a CWE -> Ontology python script if you want

**Comment by netfl0** [comment]
We need to look at the options for dealing with namespaces. AFAIK, we can take the catalog file approach, or we can develop something custom using robot and merges.

Currently I'm leaning towards the robot merge approach. We've seen very odd behavior of toolkits with the catalog file, perhaps we need to learn more about it.

Cc @hack-sentinel

**Comment by ioggstream** [comment]
> We've seen very odd behavior of toolkits with the catalog file

Feel free to share :)

**Comment by netfl0** [comment]
@hack-sentinel lets integrate the HW CWE's into this branch.

**Comment by hack-sentinel** [comment]
Now has Memory DAs merged into this feature branch.
