### ISSUE TITLE
Add Control Catalog classes to represent different release / edition / dataset / catalog

### ISSUE THREAD

**Issue by hack-sentinel** [d3fend/d3fend-ontology#74]
Create for both NIST and CCI datasets.  This will allow for metadata on versions.  For NIST 800-53 control catalog datasets, in OSCAL terms, this class would represent the catalog with metadata properties.  The External Control classes that exist will then all reference a given catalog (so refactor to point to Catalog instances rather than rely on versions strings or implicit latest load.)

**Comment by netfl0** [comment]
closed via [d758f5c](https://github.com/d3fend/d3fend-ontology/commit/d758f5c421d5a18ba4e76f5257ed18188453314a)
