### ISSUE TITLE
Update ATT&CK technique labels when they change

### ISSUE THREAD

**Issue by netfl0** [d3fend/d3fend-ontology#77]

**Comment by ioggstream** [comment]
If you clarify the requirement, I can try implementing a CI for that.

**Comment by netfl0** [comment]
I don't know if we want it to be ci just yet, but definitely automated. 

Here's a shot:

Compare T codes in d3fend-protege.ttl and their corresponding rdfs:label against T codes and name in att&ck stix document.

Output mismatches so developers can update their ontologies where indicated. Name changes may also indicate manual updates technique to DAO mappings are required.

Functionality should be added to:

https://github.com/d3fend/d3fend-ontology/blob/develop/src/util/update_attack.py

That script probably needs some improvement too. (It doesn't depend on an external library on purpose)

**Comment by ioggstream** [comment]
Can I use python3 libraries?

**Comment by nav6402** [comment]
Done, see #188
