### ISSUE TITLE
[Correction] The type of "version" data property contains inconsistencies

### ISSUE THREAD

**Issue by aw350m33d** [d3fend/d3fend-ontology#89]
Hi! I found inconsistency in the ontology:
1) For individuals `NIST_SP_800-53_R3`, `NIST_SP_800-53_R4`, `NIST_SP_800-53_R5`, the **version** property is represented _as an integer_. However, the class higher in the hierarchy `Control Catalog` contains the axiom that the version _is a string_. Similarly for the `Capability Implementation` class.
**Proposed solutions**:
a) Correct all values of data property "version" to the corresponding strings.
b) For the `Capability Implementation` and `Control Catalog` classes, specify the types for 'version' as a union: `(xsd:decimal or xsd:integer or xsd:string)`.
2) The domain of the data property "version" is 'Capability Implementation', however, this data property is also used in the 'Control Catalog' class. So the domain should be union: `('Capability Implementation' or 'Control Catalog')`.
3) Depending on the chosen solution in the first section:
a) Range of data property "version" set to `xsd:string`.
b) Set the range of data property "version" equal to the union: `(xsd:decimal or xsd:integer or xsd:string)`. 

If relevant, I can create a PR with one of the proposed solutions.

**Comment by netfl0** [comment]
I believe the correct answer is to go with making them all `xsd:string`. We would be happy to take a PR.
