### ISSUE TITLE
Maximum level of subClasses for Technique

### ISSUE THREAD

**Issue by ioggstream** [d3fend/d3fend-ontology#9]
## Question

- Is there a maximum depth of subclasses for DefensiveTechniques?
- Are there pros/cons of limiting the subclass levels?

**Comment by netfl0** [comment]
There are no maximum depths by design. This allows us to get as specific as necessary.

If it becomes unwieldy in the matrix visualization, we can address that with UI/UX elements.

**Comment by netfl0** [comment]
Please close if you feel this is addressed, open to discussion more @ioggstream
