### ISSUE TITLE
Email Filtering

### ISSUE THREAD

**Issue by kelby-shelton** [d3fend/d3fend-ontology#94]
A new technique under Isolation to describe blocking of one or more attributes of an email.

**Comment by hack-sentinel** [comment]
Whoever writes up, note this is more proactive and should be distinct from Email Deletion, which deletes after it has been stored in a server/store already.

**Comment by ryantxu1** [comment]
@netfl0 @hack-sentinel Would this go into a new column such as "File Isolation" (following 'email removal'). Though would File Isolation capture "Executable Isolation" as well.

**Comment by ryantxu1** [comment]
@netfl0 can close this now
