### ISSUE TITLE
Identifier Activity Analysis

### ISSUE THREAD

**Issue by kelby-shelton** [d3fend/d3fend-ontology#95]
A new technique under Detect > Identifier Analysis which describes the process of taking known malicious Identifiers and determining the artifacts that have interacted with those Identifiers. 

Interaction with the identifier could take the form of network traffic activity, process activity, file activity, registry activity, etc.

**Comment by hack-sentinel** [comment]
Initial version in, will update content (see #116) from recent work.

**Comment by hack-sentinel** [comment]
#116 completed/merged.  Done.
